---
- hosts: all
  become : yes
  gather_facts: no
  tasks:
  - name: install git, wget, tree on nodes
    apt:
     name: "{{ items }}"
     state: present
    with_items: 
     - git
     - wget
     - tree
